### ISSUE TITLE
Make file hides testing failures 

### ISSUE THREAD

**Issue by canyon289** [jeremiecoullon/SGMCMCJax#26]
Hello! I'm reviewing thiis library as part of https://github.com/openjournals/joss-reviews/issues/4113

In regards to testing I have two comments
1. I forgot to run `python setup.py develop` but when running the make file I don't receive any exceptions. If I run pytest independently then I see things are failing
2. I would suggest implementing a CI pipeline using github actions, or other similar service, to run tests when code is merged on main at a minimum. and ideally on each pull request as well. 
   * If i carefully pick apart the JOSS requirement "**Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?". There are no automated steps (manual steps are provided) 

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/7213793/153334980-5c7bc667-2782-4c54-84f5-8d9e6ddb5547.png">

**Comment by jeremiecoullon** [comment]
Hello! I just merged some code into the `dev` branch which addresses this issue.

Let me know if you have more questions or issues about this!
