### ISSUE TITLE
Statement of problem solved

### ISSUE THREAD

**Issue by canyon289** [jeremiecoullon/SGMCMCJax#27]
From https://github.com/openjournals/joss-reviews/issues/4113
>  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

The README describes who the target audience is, but doesn't quite articulate the problem the software was designed to solve. I assume this is solving the problem of people who want to define their models in JAX, and not a full blown PPL, but still be able too obtain samples? A sentence, or even a partial sentence would provide much clarity

**Comment by jeremiecoullon** [comment]
I made these changes to paper; let me know if you think I should clarify this some more!

**Comment by canyon289** [comment]
Looks great!
