### ISSUE TITLE
Plot labels in documentation are hard to read

### ISSUE THREAD

**Issue by canyon289** [jeremiecoullon/SGMCMCJax#28]
Black theme with black axes label on transparent background makes it challenging to see the full figure. 
![image](https://user-images.githubusercontent.com/7213793/153336440-d316e91a-9a43-475b-bdf6-dbcdd342b58e.png)

https://github.com/openjournals/joss-reviews/issues/4113

**Comment by jeremiecoullon** [comment]
I'm trying to reproduce this: I set my firefox browser to dark theme but the docs page still have a white background. 

What specifically was set to black theme in your setup?

**Comment by canyon289** [comment]
hm, I'm not sure. i tried on my laptop and its fine now.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/7213793/156863379-185416a0-192a-44af-89e1-d361212ea812.png">

**Comment by jeremiecoullon** [comment]
Other libraries (for example PyMC) seem to have similar looking plots, so I'm thinking of leaving these as they are.
What do you think?

**Comment by canyon289** [comment]
Sounds good!
