### ISSUE TITLE
Are community guidelines present?

### ISSUE THREAD

**Issue by canyon289** [jeremiecoullon/SGMCMCJax#29]
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I can't seem to find clear community guidelines, save this page on how to add a sampler
https://sgmcmcjax.readthedocs.io/en/latest/add_a_sampler.html

Per JOSS ask I suggest adding a CONTRIBUTING.md guide, or equivalent, that describes the "human process" of how to submit changes, report issues, or where to reach out to get more help. If you'd like I'm happy to explain what tools ArviZ and PyMC use for these purposes.

https://github.com/openjournals/joss-reviews/issues/4113

**Comment by jeremiecoullon** [comment]
Thanks for this suggestion!

I'll add a CONTRIBUTION.md guide following [PyMC's one](https://github.com/pymc-devs/pymc/blob/main/CONTRIBUTING.md).

ArviZ and PyMC tools: what tools do do mean?

**Comment by canyon289** [comment]
> ArviZ and PyMC tools: what tools do do mean?
Community engagement tools, like github discussion, gitter, discourse etc if people have questions or to reach out

**Comment by canyon289** [comment]
Looking over everything added this is a great start https://github.com/jeremiecoullon/SGMCMCJax/blob/master/CONTRIBUTING.md

Copying from the JOSS guidelines, I cant see to find Item 3 "seek support". If I had was seeking support how would I obtain it?  
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by jeremiecoullon** [comment]
I just added info about support in the readme and contributing.md. Let me know if there's anything else I can fix up.
