### ISSUE TITLE
Requirement clarification

### ISSUE THREAD

**Issue by ColCarroll** [jeremiecoullon/SGMCMCJax#36]
I'm not sure if it is a design decision, but if the library's only "real" dependency is jax and jaxlib (you also use tqdm, but I doubt that's "structural"). If you plan to keep it like this, I might call that out in the installation instructions -- when looking for minimum and maximum python versions, I ended up in your setup.py, then in jax's (it is Python>=3.7!)

Anyways, if you might bring on more, feel free to ignore, but that might at least deflect any installation problems over to JAX.

**Comment by jeremiecoullon** [comment]
> I might call that out in the installation instructions

I don't quite understand how to do this. Do you mean changing in setup.py the line `install_requires=["jax", "jaxlib", "tqdm"],` to `install_requires=["jax", "jaxlib"],` ?

**Comment by ColCarroll** [comment]
Oops, sorry, this was very unclear. I meant that it is cool that `jax` is the only real requirement, and I might highlight that in the README. Something like (my addition in **bold**)

SGMCMCJax is a lightweight library of stochastic gradient Markov chain Monte Carlo (SGMCMC) algorithms. The aim is to include both standard samplers (SGLD, SGHMC) as well as state of the art samplers **while requiring only JAX to run**.

**Comment by ColCarroll** [comment]
(this is not at all a requirement for the paper review either -- just a suggestion!)

**Comment by jeremiecoullon** [comment]
Done! :)
