### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ColCarroll** [jeremiecoullon/SGMCMCJax#37]
Current best practices are 

```
python -m pip install -e .
``` 
instead of 
```
python setup.py develop
```

see [a core dev here](https://discuss.python.org/t/the-difference-between-python-setup-py-build-ext-i-and-pip-install-e/3716/5), SO discussion [here](https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop).

This isn't a blocking issue, since the code works (here and on PyPI), and how you develop is your own business. For what it is worth, I also tested with `pip install -e .`, and it works fine that way too. 

(I *actually* installed `pytest-cov`, and ran `pytest -v sgmcmcjax tests --cov=sgmcmcjax --cov-report=html` to check out test coverage!)

**Comment by jeremiecoullon** [comment]
Thanks for the tips!

I fixed this in PR #45:
- changed readme
-  added code coverage to the tests in make
