### ISSUE TITLE
API documentation missing on website

### ISSUE THREAD

**Issue by ColCarroll** [jeremiecoullon/SGMCMCJax#38]
Looks like #32 you're maybe aware of this, but this might help track that, e.g., https://sgmcmcjax.readthedocs.io/en/latest/kernels.html is currently empty.

**Comment by jeremiecoullon** [comment]
This is an issue with readthedocs not finding sgmcmcjax (but it worked locally). 
Now it's finding sgmcmcjax, but not jax; so it seems that it's not installing any of the requirements. I'll investigate!

**Comment by jeremiecoullon** [comment]
Finally fixed!

**Comment by ColCarroll** [comment]
Looks great! https://github.com/openjournals/joss-reviews/issues/4113
