### ISSUE TITLE
Possible additional reference?

### ISSUE THREAD

**Issue by ColCarroll** [jeremiecoullon/SGMCMCJax#39]
The Nemeth and Fearnhead reference looks very nice! I had somewhat expected Ma, Chen, and Fox's [A Complete Recipe for Stochastic Gradient MCMC](https://proceedings.neurips.cc/paper/2015/hash/9a4400501febb2a95e79248486a5f6d3-Abstract.html) to be a reference (I see Nemeth and Fearnhead do point to it a bit, particularly in section 3). 

Is it reasonable to add that (or some similar, previous work)?

**Comment by jeremiecoullon** [comment]
I added this reference to the paper

**Comment by ColCarroll** [comment]
(adding backlinks to https://github.com/openjournals/joss-reviews/issues/4113)
