### ISSUE TITLE
Clarify introduction

### ISSUE THREAD

**Issue by ColCarroll** [jeremiecoullon/SGMCMCJax#40]
My two questions/suggestions for the Summary of the paper: 
1. Clarify that these are gradient-based MCMC methods - I would expect a non-expert might hear MCMC and think about Metropolis-Hastings or Gibbs rather than HMC-type samplers.
2. the sentence beginning "innovations in these algorithms include..." : can you clarify whether it is this library doing the innovating, or current research (perhaps aided by the library!)

**Comment by jeremiecoullon** [comment]
I made changes to the paper to clarify these points. Let me know if I could clarify this some more!

**Comment by ColCarroll** [comment]
thanks!

**Comment by ColCarroll** [comment]
(adding backlinks https://github.com/openjournals/joss-reviews/issues/4113)
